package com.sj.web.domain;

import java.util.Date;

public class TsysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.login_pwd
     *
     * @mbg.generated
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.org_id
     *
     * @mbg.generated
     */
    private Integer orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.mobile_tel
     *
     * @mbg.generated
     */
    private String mobileTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.user_status
     *
     * @mbg.generated
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.login_error_times
     *
     * @mbg.generated
     */
    private Integer loginErrorTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsys_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.user_id
     *
     * @return the value of tsys_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.user_id
     *
     * @param userId the value for tsys_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.user_name
     *
     * @return the value of tsys_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.user_name
     *
     * @param userName the value for tsys_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.login_pwd
     *
     * @return the value of tsys_user.login_pwd
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.login_pwd
     *
     * @param loginPwd the value for tsys_user.login_pwd
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.org_id
     *
     * @return the value of tsys_user.org_id
     *
     * @mbg.generated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.org_id
     *
     * @param orgId the value for tsys_user.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.mobile_tel
     *
     * @return the value of tsys_user.mobile_tel
     *
     * @mbg.generated
     */
    public String getMobileTel() {
        return mobileTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.mobile_tel
     *
     * @param mobileTel the value for tsys_user.mobile_tel
     *
     * @mbg.generated
     */
    public void setMobileTel(String mobileTel) {
        this.mobileTel = mobileTel == null ? null : mobileTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.user_status
     *
     * @return the value of tsys_user.user_status
     *
     * @mbg.generated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.user_status
     *
     * @param userStatus the value for tsys_user.user_status
     *
     * @mbg.generated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.login_error_times
     *
     * @return the value of tsys_user.login_error_times
     *
     * @mbg.generated
     */
    public Integer getLoginErrorTimes() {
        return loginErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.login_error_times
     *
     * @param loginErrorTimes the value for tsys_user.login_error_times
     *
     * @mbg.generated
     */
    public void setLoginErrorTimes(Integer loginErrorTimes) {
        this.loginErrorTimes = loginErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.gmt_create
     *
     * @return the value of tsys_user.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.gmt_create
     *
     * @param gmtCreate the value for tsys_user.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.gmt_modify
     *
     * @return the value of tsys_user.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.gmt_modify
     *
     * @param gmtModify the value for tsys_user.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsys_user.remark
     *
     * @return the value of tsys_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsys_user.remark
     *
     * @param remark the value for tsys_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}