package com.sj.web.mapper;

import com.sj.web.domain.TsysUser;
import com.sj.web.domain.TsysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    long countByExample(TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int deleteByExample(TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int insert(TsysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int insertSelective(TsysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    List<TsysUser> selectByExample(TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    TsysUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TsysUser record, @Param("example") TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TsysUser record, @Param("example") TsysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsysUser record);
}